version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  web-crawler-api:
    image: gabardomateus/web-crawler-api
    container_name: web-crawler-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/postgres"
  web-crawler-cifras:
    image: gabardomateus/web-crawler-cifras
    container_name: web-crawler-cifras
    ports:
      - "9080:9080"
    environment:
      DB_HOST: "postgres"
  web-crawler-scheduler:
    image: gabardomateus/web-crawler-scheduler
    container_name: web-crawler-scheduler
    ports:
      - "8081:8081"